### ISSUE TITLE
See how much time is left on an active timer

### ISSUE THREAD

**Issue by khaliqgant** [Alxmerino/alfred-countdown-timer#2]

**Comment by khaliqgant** [comment]
So...@Alxmerino ...started to write some code, then did some research on this and I think it might just be better to use an app for this instead. There are a few different options
• [Vitamin R](http://www.publicspace.net/Vitamin-R/)
• [Gestimer](http://maddin.io/gestimer/)
• [Tyme](http://tyme-app.com/mac-2/)
• [Howler app](https://itunes.apple.com/us/app/howler-timer/id428846772?mt=12) - a bit dated, but honestly might simple enough to get the job done

I found this as well which is a seemingly improved version of what we're using: http://geekzone.philosophicalzombie.net/.

Either way, I think an app is probably the best way to go. Closing this issue. Feel free to open if you think it still make sense to make a more customizable version.

**Comment by Alxmerino** [comment]
@khaliqgant sounds good to me, will be giving these a try see which one fits best, thanks
